[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify CMS
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Enable Git Gateway for CMS
[build.environment]
  GIT_LFS_ENABLED = "true"

# CMS configuration
[context.production.environment]
  GIT_LFS_ENABLED = "true"

[context.deploy-preview.environment]
  GIT_LFS_ENABLED = "true" 