# Netlify configuration for CMS access only
# Main hosting is handled by AWS Amplify

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Enable Git Gateway for CMS
[build.environment]
  GIT_LFS_ENABLED = "true" 